# Generated by Django 2.1.5 on 2020-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200219_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=10),
        ),
    ]
